#!/usr/bin/env node
'use strict';

/**
 * One-time setup script.
 * Generates a .env file with fresh cryptographic keys.
 *
 * Usage:  node scripts/setup.js
 */

const crypto = require('crypto');
const fs     = require('fs');
const path   = require('path');

const ENV_PATH = path.join(__dirname, '../.env');

if (fs.existsSync(ENV_PATH)) {
  console.log('[setup] .env already exists — skipping. Delete it and re-run to regenerate.');
  process.exit(0);
}

const encryptionKey = crypto.randomBytes(32).toString('hex');
const hmacKey       = crypto.randomBytes(32).toString('hex');
const jwtSecret     = crypto.randomBytes(48).toString('hex');
const pgPassword    = crypto.randomBytes(24).toString('hex');

const content = `# Auto-generated by scripts/setup.js
# DO NOT COMMIT THIS FILE — it contains live cryptographic secrets.

NODE_ENV=development
PORT=3000
LOG_LEVEL=info

# ── Encryption ──────────────────────────────────────────────────────────────
# AES-256-GCM key  (32 bytes / 64 hex chars)
ENCRYPTION_KEY=${encryptionKey}

# HMAC-SHA256 key for indexed-lookup tokens (32 bytes / 64 hex chars)
HMAC_KEY=${hmacKey}

# ── JWT ─────────────────────────────────────────────────────────────────────
JWT_SECRET=${jwtSecret}

# ── PostgreSQL ───────────────────────────────────────────────────────────────
# Use "postgres" as host when running inside docker-compose.
# Use "localhost" for local development outside Docker.
DATABASE_URL=postgresql://wallet_user:${pgPassword}@postgres:5432/wallet_db
DATABASE_SSL=false

# These vars are consumed by the postgres docker-compose service
POSTGRES_DB=wallet_db
POSTGRES_USER=wallet_user
POSTGRES_PASSWORD=${pgPassword}

# ── Rate limiting (optional overrides) ──────────────────────────────────────
# RATE_LIMIT_WINDOW_MS=60000
# RATE_LIMIT_GLOBAL_MAX=100
# RATE_LIMIT_AUTH_MAX=10
# RATE_LIMIT_WALLET_MAX=30
`;

fs.writeFileSync(ENV_PATH, content, { mode: 0o600 });
console.log('[setup] .env created with fresh keys.');
console.log('[setup] Start the API with: docker-compose up  OR  npm run dev');
